group theory
thomastanck/cochs pull request #3
Opened 2019-10-30 12:17 UTC by gerhean

2019-10-30 12:35 UTC, qjqqyy approved these changes
lgtm

2019-11-02 02:08 UTC, thomastanck requested changes
Could you add tests to the Makefile under `test:`?

Also, your files have a lot of trailing spaces. could you quickly get rid of them as well?

2019-11-02 02:08 UTC, thomastanck commented on examples/groups.coc
> +define rIdAndrInvImpliesUniqueId =
Remove commented code

2019-11-02 03:17 UTC, gerhean commented on examples/groups.coc
> +define rIdAndrInvImpliesUniqueId =
done

2019-11-02 03:24 UTC, thomastanck approved these changes
Very nice. Good job!

2019-11-02 03:24 UTC, merged